# name of the applied model
model_name: 'AdaIN'

# data preparation for the network training and testing
# the input of the network architecture
default_size: 256
content_size: 512
style_size: 512

# regularization of the network kernels
weight_decay: 0.0005
trainable_scopes: 'image_decoder'

# perceptual loss config
network_name: 'vgg_19'
checkpoint_path: '/DATA/lsheng/model_zoo/VGG/vgg_19.ckpt'
checkpoint_exclude_scopes: 'vgg_19/fc'
ignore_missing_vars: True

# content loss layers
content_loss_layers:
  - 'conv4/conv4_1'
style_loss_layers:
  - 'conv1/conv1_1'
  - 'conv2/conv2_1'
  - 'conv3/conv3_1'
  - 'conv4/conv4_1'

# loss weights
content_weight: 1.0
style_weight: 0.01
tv_weight: 0
