# name of the applied model
model_name: 'MSG'

# data preparation for the network training and testing
# the input of the network architecture
default_size: 256
content_size: 512
style_size: 512

# the network learning scheme
weight_decay: 0.0005
trainable_scopes: 'feature_extractor, feature_decoder, feature_processing, inspiration'

# perceptual loss config
network_name: 'vgg_16'
checkpoint_path: '/DATA/lsheng/model_zoo/VGG/vgg_16.ckpt'
checkpoint_exclude_scopes: 'vgg_16/fc'
ignore_missing_vars: True

# content loss layers
content_loss_layers:
  - 'conv2/conv2_2'
style_loss_layers:
  - 'conv1/conv1_2'
  - 'conv2/conv2_2'
  - 'conv3/conv3_3'
  - 'conv4/conv4_3'

# loss weights
content_weight: 1.0
style_weight: 5.0
tv_weight: 1.0

